FROM fedora

MAINTAINER Kamesh Sampath, kamesh.sampath@hotmail.com

# Update the repo
RUN yum -y update

# Install and setup project dependencies
RUN yum -y install curl unzip wget supervisor openssh-server rsyslog rsync

CMD ["bash"]

